### ISSUE TITLE
Convert MCA (Anvil) to TNT fails on backup region files 

### ISSUE THREAD

**Issue by TropicalShadow** [EmortalMC/TNT#2]
This isn't a major issue, but I found a issue while converting an Anvil world it threw an error

`Unexpected exception thrown: java.lang.NumberFormatException: For input string: "mca"`

I found that it was trying to read `r.0.0.mca.2710657221739100675.backup`
This line [here](https://github.com/EmortalMC/TNT/blob/ecda3972cb3a9b87e20a78a92f301bfdde1c4315/src/main/kotlin/dev/emortal/tnt/TNT.kt#L113) reads the last two items in the array... which from the backup file is ["mca", "2710657221739100675"]

My suggestion to fix it would be 
Replace `val args = it.nameWithoutExtension.split(".").takeLast(2)` with

-  Regex - Something along the lines of `val args = Regex("(-?\\d+).(-?\\d+)").find(it.nameWithoutExtension)?.groupValues?.drop(0)`
-  `val args = it.nameWithoutExtension.split(".").slice(1..2)`

**Comment by MrlnHi** [comment]
PR your suggestion maybe

**Comment by TropicalShadow** [comment]
> PR your suggestion maybe

I was going to but as there are many different ways to resolve this issue I couldn’t figure out which was the best, so I thought the repo owner may have more knowledge and is able to choose the correct result.

**Comment by emortaldev** [comment]
Turns out this was fixed in [723cb52](https://github.com/emortalmc/TNT/commit/723cb527d1645e5f86be7c20ef3a32966dcb424b)!
